# Generated by Django 5.1.5 on 2025-02-05 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20, verbose_name='Dia da Semana')),
                ('horario_inicio_expediente', models.TimeField(verbose_name='Início do Expediente')),
                ('horario_fim_expediente', models.TimeField(verbose_name='Fim do Expediente')),
                ('horario_inicio_almoco', models.TimeField(blank=True, null=True, verbose_name='Início do Almoço')),
                ('horario_fim_almoco', models.TimeField(blank=True, null=True, verbose_name='Fim do Almoço')),
                ('grupo_permissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='auth.group', verbose_name='Grupo de Permissão')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Técnico')),
                ('status', models.CharField(choices=[('Em Atividade', 'Em Atividade'), ('Fora Expediente', 'Fora Expediente'), ('Disponível', 'Disponível')], default='Disponível', max_length=20, verbose_name='Status')),
                ('grupos', models.ManyToManyField(related_name='tecnicos', to='auth.group', verbose_name='Grupos de Permissão')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ordem_servico', models.CharField(max_length=50, unique=True, verbose_name='ID da Ordem de Serviço')),
                ('numero_ordem_servico', models.CharField(max_length=50, verbose_name='Número da Ordem de Serviço')),
                ('data_cadastro', models.DateTimeField(verbose_name='Data de Cadastro')),
                ('data_inicio_programado', models.DateTimeField(verbose_name='Data de Início Programado')),
                ('data_termino_programado', models.DateTimeField(verbose_name='Data de Término Programado')),
                ('data_inicio_executado', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início Executado')),
                ('data_termino_executado', models.DateTimeField(blank=True, null=True, verbose_name='Data de Término Executado')),
                ('prazo', models.DurationField(verbose_name='Prazo')),
                ('id_cliente_servico', models.CharField(max_length=50, verbose_name='ID do Cliente')),
                ('tipo_os', models.CharField(max_length=50, verbose_name='Tipo da OS')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('ultima_mensagem', models.TextField(blank=True, null=True, verbose_name='Última Mensagem')),
                ('tecnicos', models.ManyToManyField(related_name='ordens_servico', to='tecnicos.tecnico', verbose_name='Técnicos')),
            ],
        ),
    ]
