# Generated by Django 5.1.5 on 2025-02-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='escala',
            field=models.CharField(choices=[('5x2', '5x2 - Segunda a Sexta'), ('6x1', '6x1 - Segunda a Sábado'), ('12x36', '12x36 - 12h de trabalho, 36h de descanso'), ('Turno Fixo', 'Turno Fixo (exemplo: 08h às 18h)'), ('Turno Noturno', 'Turno Noturno (exemplo: 22h às 06h)'), ('Personalizado', 'Personalizado')], default='5x2', max_length=20, verbose_name='Escala de Trabalho'),
        ),
    ]
