# Generated by Django 5.1.5 on 2025-02-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(max_length=20, verbose_name='status_os'),
        ),
    ]
