# Generated by Django 5.1.5 on 2025-02-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0002_expediente_escala'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='dia_semana',
        ),
        migrations.AddField(
            model_name='expediente',
            name='dias_semana',
            field=models.ManyToManyField(to='tecnicos.diasemana', verbose_name='Dias da Semana'),
        ),
    ]
