# Generated by Django 5.1.5 on 2025-02-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0002_alter_ordemservico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='ultima_atualizacao_status',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização do Status'),
        ),
    ]
