# Generated by Django 5.1.5 on 2025-02-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0003_tecnico_ultima_atualizacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='setor',
            field=models.CharField(choices=[('Técnico - Varejo', 'Técnico - Varejo'), ('Técnico - Varejo/Atacado', 'Técnico - Varejo/Atacado'), ('Operacional - Varejo', 'Operacional - Varejo')], default='Técnico - Varejo', max_length=50, verbose_name='Setor'),
        ),
    ]
