# Generated by Django 5.1.5 on 2025-02-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0003_diasemana_remove_expediente_dia_semana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='id',
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='id_ordem_servico',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID da Ordem de Serviço'),
        ),
    ]
