# Generated by Django 5.1.5 on 2025-02-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0004_tecnico_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='setor',
            field=models.CharField(choices=[('Megalink', 'Megalink'), ('BJ Fibra', 'BJ Fibra')], default='Megalink', max_length=50, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='status',
            field=models.CharField(choices=[('Em Atividade', 'Em Atividade'), ('Fora Expediente', 'Fora Expediente'), ('Disponível', 'Disponível'), ('Ajudante', 'Ajudante')], default='Fora Expediente', max_length=20, verbose_name='Status'),
        ),
    ]
