# Generated by Django 5.1.5 on 2025-02-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0004_remove_ordemservico_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='id_ordem_servico',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID da Ordem de Serviço'),
        ),
    ]
