# Generated by Django 5.1.5 on 2025-02-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0005_alter_ordemservico_id_ordem_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='status',
        ),
    ]
