# Generated by Django 5.1.5 on 2025-02-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0005_alter_tecnico_setor_alter_tecnico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='cidade',
            field=models.CharField(choices=[('Água Branca', 'Água Branca'), ('Alagoinha Do Piauí', 'Alagoinha Do Piauí'), ('Amarante', 'Amarante'), ('Angical Do Piauí', 'Angical Do Piauí'), ('Aroazes', 'Aroazes'), ('Balsas', 'Balsas'), ('Barão De Grajaú', 'Barão De Grajaú'), ('Batalha', 'Batalha'), ('Caridade Do Piauí', 'Caridade Do Piauí'), ('Caxias', 'Caxias'), ('Cocal', 'Cocal'), ('Colinas', 'Colinas'), ('Colônia Do Gurguéia', 'Colônia Do Gurguéia'), ('Corrente', 'Corrente'), ('Eliseu Martins', 'Eliseu Martins'), ('Floriano', 'Floriano'), ('Formosa Do Rio Preto', 'Formosa Do Rio Preto'), ('Fortaleza', 'Fortaleza'), ('Fronteiras', 'Fronteiras'), ('Geminiano', 'Geminiano'), ('Guadalupe', 'Guadalupe'), ('Imperatriz', 'Imperatriz'), ('Ipiranga Do Piauí', 'Ipiranga Do Piauí'), ('Isaías Coelho', 'Isaías Coelho'), ('Itainópolis', 'Itainópolis'), ('Itapecuru Mirim', 'Itapecuru Mirim'), ('Landri Sales', 'Landri Sales'), ('Manaus', 'Manaus'), ('Matões', 'Matões'), ('Monsenhor Gil', 'Monsenhor Gil'), ('Nazaré Do Piauí', 'Nazaré Do Piauí'), ('Nazária', 'Nazária'), ('Oeiras', 'Oeiras'), ('Parnarama', 'Parnarama'), ('Paulistana', 'Paulistana'), ('Picos', 'Picos'), ('Pimenteiras', 'Pimenteiras'), ('Piripiri', 'Piripiri'), ('Presidente Dutra', 'Presidente Dutra'), ('Recife', 'Recife'), ('Regeneração', 'Regeneração'), ('Santana Do Maranhão', 'Santana Do Maranhão'), ('São Francisco Do Piauí', 'São Francisco Do Piauí'), ('São João Do Piauí', 'São João Do Piauí'), ('São Luís', 'São Luís'), ('São Paulo', 'São Paulo'), ('São Pedro Do Piauí', 'São Pedro Do Piauí'), ('Simplício Mendes', 'Simplício Mendes'), ('Sussuapara', 'Sussuapara'), ('Teresina', 'Teresina'), ('Tutóia', 'Tutóia'), ('Urbano Santos', 'Urbano Santos'), ('Valença Do Piauí', 'Valença Do Piauí'), ('Vera Mendes', 'Vera Mendes')], default='Floriano', max_length=50, verbose_name='Cidade'),
        ),
    ]
